### ISSUE TITLE
How to define the initial scale of the jump distribution?

### ISSUE THREAD

**Issue by scheidan** [mvihola/AdaptiveMCMC.jl#9]
I may have missed it in the documentation: is there a way to define the scale of the initial jump distribution? This would be useful because the parameters may have very different orders of magnitude (which is often know from the prior).

Thanks for the great package!

**Comment by mvihola** [comment]
Thanks for a good question. I had not thought about this use case at all, but it can certainly help the initial mixing and adaptation if you provide a good starting value for the adapted scale/shape matrix.

To make this slightly more ergonomic, I added a possibility to provide keyword arguments to the Adaptive MCMC algorithm constructors. Here's an example with the new interface, which uses RAM with given initial shape (rather than default identity):

```{julia}
using AdaptiveMCMC, LinearAlgebra

log_p(x) = -100x[1]^2 - x[2]^2 - 0.01x[3]^2
x0 = zeros(3)
S0 = cholesky(diagm([0.01,1,100]))
ram_state = RobustAdaptiveMetropolis(x0; S_init = S0)
default_init = adaptive_rwm(x0, log_p, 1000)
good_init = adaptive_rwm(x0, log_p, 1000; algorithm = [ram_state])
```

**Comment by scheidan** [comment]
Thanks a lot!
